//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvertisingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annonser
    {
        public int addId { get; set; }
        public string resources { get; set; }
        public string onHooverText { get; set; }
    }
}
