//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grup__8_Annonser.ServiceReferenceAnnons {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnonsKlass", Namespace="http://schemas.datacontract.org/2004/07/Grup__8_Annonser")]
    [System.SerializableAttribute()]
    public partial class AnnonsKlass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HooverTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResursField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HooverText {
            get {
                return this.HooverTextField;
            }
            set {
                if ((object.ReferenceEquals(this.HooverTextField, value) != true)) {
                    this.HooverTextField = value;
                    this.RaisePropertyChanged("HooverText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resurs {
            get {
                return this.ResursField;
            }
            set {
                if ((object.ReferenceEquals(this.ResursField, value) != true)) {
                    this.ResursField = value;
                    this.RaisePropertyChanged("Resurs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAnnons.IServiceAnnons")]
    public interface IServiceAnnons {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAnnons/DoWork", ReplyAction="http://tempuri.org/IServiceAnnons/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAnnons/DoWork", ReplyAction="http://tempuri.org/IServiceAnnons/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAnnons/ReadAnnons", ReplyAction="http://tempuri.org/IServiceAnnons/ReadAnnonsResponse")]
        Grup__8_Annonser.ServiceReferenceAnnons.AnnonsKlass[] ReadAnnons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAnnons/ReadAnnons", ReplyAction="http://tempuri.org/IServiceAnnons/ReadAnnonsResponse")]
        System.Threading.Tasks.Task<Grup__8_Annonser.ServiceReferenceAnnons.AnnonsKlass[]> ReadAnnonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAnnons/CreateAnnons", ReplyAction="http://tempuri.org/IServiceAnnons/CreateAnnonsResponse")]
        void CreateAnnons(string Resurs, string HooverText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAnnons/CreateAnnons", ReplyAction="http://tempuri.org/IServiceAnnons/CreateAnnonsResponse")]
        System.Threading.Tasks.Task CreateAnnonsAsync(string Resurs, string HooverText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAnnonsChannel : Grup__8_Annonser.ServiceReferenceAnnons.IServiceAnnons, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAnnonsClient : System.ServiceModel.ClientBase<Grup__8_Annonser.ServiceReferenceAnnons.IServiceAnnons>, Grup__8_Annonser.ServiceReferenceAnnons.IServiceAnnons {
        
        public ServiceAnnonsClient() {
        }
        
        public ServiceAnnonsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAnnonsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAnnonsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAnnonsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public Grup__8_Annonser.ServiceReferenceAnnons.AnnonsKlass[] ReadAnnons() {
            return base.Channel.ReadAnnons();
        }
        
        public System.Threading.Tasks.Task<Grup__8_Annonser.ServiceReferenceAnnons.AnnonsKlass[]> ReadAnnonsAsync() {
            return base.Channel.ReadAnnonsAsync();
        }
        
        public void CreateAnnons(string Resurs, string HooverText) {
            base.Channel.CreateAnnons(Resurs, HooverText);
        }
        
        public System.Threading.Tasks.Task CreateAnnonsAsync(string Resurs, string HooverText) {
            return base.Channel.CreateAnnonsAsync(Resurs, HooverText);
        }
    }
}
