//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grup__8_Annonser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annons
    {
        public int AnnonsID { get; set; }
        public string Resurs { get; set; }
        public string On_hoover_text { get; set; }
        public string Felmeddelande { get; set; }
        public Nullable<double> Höjd { get; set; }
        public Nullable<double> Längd { get; set; }
    }
}
