//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFOrderAuto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoppingDBEntities4 : DbContext
    {
        public ShoppingDBEntities4()
            : base("name=ShoppingDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Produkt> Produkt { get; set; }
        public virtual DbSet<ProduktTillagd> ProduktTillagd { get; set; }
        public virtual DbSet<Varukorg> Varukorg { get; set; }
    }
}
