//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFOrderAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduktTillagd
    {
        public int TransaktionId { get; set; }
        public int VarukorgId { get; set; }
        public int ProduktId { get; set; }
        public int Antal { get; set; }
        public decimal SummaProdukter { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        public virtual Varukorg Varukorg { get; set; }
    }
}
