//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFSpelarPortalAdmin1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingTable
    {
        public int RankingId { get; set; }
        public int TeamId { get; set; }
        public int PlayedGames { get; set; }
        public int WonGames { get; set; }
        public int DrawGames { get; set; }
        public int LostGames { get; set; }
        public int Points { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
